name: Github Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build the thing
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event ${{github.event_name}}"
      - run: echo "Event ${{github.ref}}"
      - uses: actions/checkout@v3.3.0
      - run: tree
      
